
highchart() %>% 
  hc_chart(events = list(
    drilldown = JS(zone_js), 
    drillup = JS(zone_js2))) %>% 
  hc_add_series(name = names_str[1], 
                data = list(list(drilldown = TRUE, drilldownName = "A_4", 
                                 NAME = "zone1")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[1], 
                mapData = list(x=1,type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[1]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>% 
  hc_add_series(name = names_str[2], 
                data = list(list(drilldown = TRUE, drilldownName = "D_5", 
                                 NAME = "zone2")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[2], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[2]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>% 
  hc_add_series(name = names_str[3], 
                data = list(list(drilldown = TRUE, drilldownName = "C_1", 
                                 NAME = "zone3")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[3], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[3]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>% 
  hc_add_series(name = names_str[4], 
                data = list(list(drilldown = TRUE, drilldownName = "A_1", 
                                 NAME = "zone4")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[4], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[4]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>% 
  hc_add_series(name = names_str[5], 
                data = list(list(drilldown = TRUE, drilldownName = "A_2", 
                                 NAME = "zone5")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[5], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[5]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>% 
  hc_add_series(name = names_str[6], 
                data = list(list(drilldown = TRUE, drilldownName = "A_3", 
                                 NAME = "zone6")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[6], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[6]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>% 
  hc_add_series(name = names_str[7], 
                data = list(list(drilldown = TRUE, drilldownName = "A_5", 
                                 NAME = "zone7")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[7], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[7]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>% 
  hc_add_series(name = names_str[8], 
                data = list(list(drilldown = TRUE, drilldownName = "B_1", 
                                 NAME = "zone8")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[8], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[8]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>%
  hc_add_series(name = names_str[9], 
                data = list(list(drilldown = TRUE, drilldownName = "B_2", 
                                 NAME = "zone9")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[9], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[9]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>% 
  hc_add_series(name = names_str[10], 
                data = list(list(drilldown = TRUE, drilldownName = "B_3", 
                                 NAME = "zone10")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[10], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[10]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>%
  hc_add_series(name = names_str[11], 
                data = list(list(drilldown = TRUE, drilldownName = "B_4", 
                                 NAME = "zone11")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[11], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[11]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>%
  hc_add_series(name = names_str[12], 
                data = list(list(drilldown = TRUE, drilldownName = "B_5", 
                                 NAME = "zone12")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[12], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[12]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>%
  hc_add_series(name = names_str[13], 
                data = list(list(drilldown = TRUE, drilldownName = "B_6", 
                                 NAME = "zone13")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[13], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[13]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>%
  hc_add_series(name = names_str[14], 
                data = list(list(drilldown = TRUE, drilldownName = "C_2", 
                                 NAME = "zone14")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[14], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[14]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>%
  hc_add_series(name = names_str[15], 
                data = list(list(drilldown = TRUE, drilldownName = "C_3", 
                                 NAME = "zone15")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[15], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[15]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>%
  hc_add_series(name = names_str[16], 
                data = list(list(drilldown = TRUE, drilldownName = "C_4", 
                                 NAME = "zone16")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[16], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[16]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>%
  hc_add_series(name = names_str[17], 
                data = list(list(drilldown = TRUE, drilldownName = "C_5", 
                                 NAME = "zone17")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[17], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[17]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>%
  hc_add_series(name = names_str[18], 
                data = list(list(drilldown = TRUE, drilldownName = "C_6", 
                                 NAME = "zone18")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[18], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[18]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>% 
  hc_add_series(name = names_str[19], 
                data = list(list(drilldown = TRUE, drilldownName = "C_7", 
                                 NAME = "zone19")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[19], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[19]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>%
  hc_add_series(name = names_str[20], 
                data = list(list(drilldown = TRUE, drilldownName = "D_1", 
                                 NAME = "zone20")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[20], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[20]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>% 
  hc_add_series(name = names_str[21], 
                data = list(list(drilldown = TRUE, drilldownName = "D_2", 
                                 NAME = "zone21")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[21], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[21]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>%
  hc_add_series(name = names_str[22], 
                data = list(list(drilldown = TRUE, drilldownName = "D_3", 
                                 NAME = "zone22")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[22], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[22]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>% 
  hc_add_series(name = names_str[23], 
                data = list(list(drilldown = TRUE, drilldownName = "D_4", 
                                 NAME = "zone23")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[23], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[23]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>%
  hc_add_series(name = names_str[24], 
                data = list(list(drilldown = TRUE, drilldownName = "D_6", 
                                 NAME = "zone24")),
                joinBy = "NAME", 
                borderColor = "#c7c3c3",
                color = colors_str[24], 
                mapData = list(x = 1, type = "FeatureCollection", 
                               features = durham_redline_json$features[zone_idx[24]]),
                type = "map", geojson = TRUE, 
                showInLegend = FALSE,  tooltip = list(pointFormat = "")) %>% 
  hc_title(text = list("Redlining in Durham"), 
           style = list(fontFamily = "Montserrat", fontWeight = "bold")) 